//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeddingWebsiteMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfirmationCodeLog
    {
        public int AttemptId { get; set; }
        public string ConfirmationCode { get; set; }
        public System.DateTime AttemptDateTime { get; set; }
    }
}
