//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeddingWebsiteMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GuestBookEntry
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Entry { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<bool> Approved { get; set; }
        public Nullable<System.DateTime> ApprovedOn { get; set; }
    }
}
