//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeddingWebsiteMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsaZipCode
    {
        public int Id { get; set; }
        public Nullable<int> Zip { get; set; }
        public Nullable<decimal> Lat { get; set; }
        public Nullable<decimal> Long { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public Nullable<int> Pop { get; set; }
        public string CountyName { get; set; }
        public Nullable<decimal> CountyWeight { get; set; }
    }
}
